services:
  frontend:
    build: ./frontend
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    init: true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  db:
    image: mysql:26.7.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3308:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3002:3000
      - 9229:9229
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/package.json

volumes:
  frontend_node_modules:
  mysql_data:
